# -*- coding: utf-8 -*-
"""movie_recommender_system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zr0MZN9-MSOS2mXCehKg0k8xKdli9TzJ
"""

import pandas as pd

movies=pd.read_csv('/content/top10K-TMDB-movies.csv')

movies.head()

movies.head(10)

movies.describe()

movies.info()

movies.isnull().sum()

movies=movies[['id', 'title', 'overview', 'genre']]

movies

movies['tags'] = movies['overview']+movies['genre']

movies

new_data  = movies.drop(columns=['overview', 'genre'])

new_data

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=10000, stop_words='english')

cv

vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

vector.shape

from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vector)

similarity

new_data[new_data['title']=="The Godfather"].index[0]

distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

def recommand(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

recommand("Iron Man")

recommand("Avatar")

recommand("The Godfather")

recommand("The Dark Knight")

recommand("The Shawshank Redemption")